### ISSUE TITLE
Background Playing

### ISSUE THREAD

**Issue by swiftuinidev** [SvenTiigi/YouTubePlayerKit#29] opened 2022-06-13 19:38 UTC
Is it possible with this player to allow background playing to continue if so can you link me to the docs that describe it thanks

**Comment by SvenTiigi** [comment] 2022-06-13 21:05
Duplicate of https://github.com/SvenTiigi/YouTubePlayerKit/issues/8

**Closed by SvenTiigi** 2022-06-13 21:05 UTC
Labels: help wanted
