### ISSUE TITLE
background play

### ISSUE THREAD

**Issue by yongbeomkwak** [SvenTiigi/YouTubePlayerKit#38] opened 2022-08-21 07:38 UTC
Hello everybody
I am trying to develop a personal music app using youtube with your package.

How do I keep YouTube videos playing? even by pressing the home button.

**Comment by SvenTiigi** [comment] 2022-08-26 07:57
Duplicate of https://github.com/SvenTiigi/YouTubePlayerKit/issues/8

**Closed by SvenTiigi** 2022-08-26 07:57 UTC
