### ISSUE TITLE
Inconsistent fullscreen behavior between iPhone and iPad

### ISSUE THREAD

**Issue by kiddosai** [SvenTiigi/YouTubePlayerKit#86] opened 2024-03-28 08:39 UTC
### What happened?

"playInline: false, fullscreenMode: .system" configuration automatically play video in fullscreen on iPhone but not on iPad. In other words how to get similar behavior on iPad?

### What are the steps to reproduce?

var youTube: YouTubePlayer = YouTubePlayer(configuration: .init(
        automaticallyAdjustsContentInsets: true,
        allowsPictureInPictureMediaPlayback: false,
        fullscreenMode: .system,
        autoPlay: false,
        showControls: false,
        keyboardControlsDisabled: true,
        showFullscreenButton: false,
        showAnnotations: false,
        loopEnabled: false,
        useModestBranding: true,
        playInline: false,
        showRelatedVideos: false

### What is the expected behavior?

Similar behavior in iPad than iPhone

**Comment by SvenTiigi** [comment] 2024-03-28 12:39
Duplicate of https://github.com/SvenTiigi/YouTubePlayerKit/issues/52

**Closed by SvenTiigi** 2024-03-28 12:39 UTC
Labels: bug

**Comment by kiddosai** [comment] 2024-03-30 17:57
(Thank you for being so reactive)
