### ISSUE TITLE
Fullscreen unavailable

### ISSUE THREAD

**Issue by frlefebvre** [SvenTiigi/YouTubePlayerKit#58] opened 2023-01-30 16:13 UTC
### What happened?

The ability to make videos fullscreen is now unavailable on iPad but still works on iOS. This was working a few days ago until I updated the library so I'm unsure if this is a new Youtube limitation or not.

### What are the steps to reproduce?

- Setup a YouTubePlayerKit view with as normal
- When tapping the full screen button in the YouTube player on iPad, a tool tip indicates that my browser doesn't support full screen. Doing the same on iOS works however.
- If the `playInline` configuration property is set to false, the video plays in line too

### What is the expected behavior?

I'd expect full screen to work on both device types but I appreciate this may be a YouTube limitation. Any guidance here would be greatly appreciated!

**Comment by SvenTiigi** [comment] 2023-01-30 16:41
Duplicate of https://github.com/SvenTiigi/YouTubePlayerKit/issues/52

**Closed by SvenTiigi** 2023-01-30 16:41 UTC
Labels: bug, youtube-player-iframe-api-bug
