### ISSUE TITLE
Open external links in App context (currently open externally in Safari) 

### ISSUE THREAD

**Issue by erank3** [SvenTiigi/YouTubePlayerKit#31] opened 2022-07-05 13:09 UTC
# Motivation
> ℹ Please replace this with your motivation. For example if your feature request is related to a problem.

Ideally I would want to prevent opening external links that are triggered by the player browser - however I understand this goes against YouTube TOS so at least I would prefer to open links inside the apps.

# Solution
> ℹ Please replace this with your proposed solution.
Based on this:
https://stackoverflow.com/questions/30603671/open-a-wkwebview-target-blank-link-in-safari

This behavior can be achieved by hooking into [WKNavigationDelegate](https://developer.apple.com/documentation/webkit/wknavigationdelegate)

However the player web view is private 
 /// The YouTubePlayerWebView
    private let webView: YouTubePlayerWebView

The easy option would be making the player view public.

A more complicated solution would be actually implementing WKNavigationDelegate
[https://stackoverflow.com/questions/30603671/open-a-wkwebview-target-blank-link-in-safari]

override func loadView() {
    super.loadView()
    self.webView.navigationDelegate = self 
    self.webView.uiDelegate = self  //must have this
}

func webView(_ webView: WKWebView,
               createWebViewWith configuration: WKWebViewConfiguration,
               for navigationAction: WKNavigationAction,
               windowFeatures: WKWindowFeatures) -> WKWebView? {
    if navigationAction.targetFrame == nil, let url = navigationAction.request.url {
      if url.description.lowercased().range(of: "http://") != nil ||
        url.description.lowercased().range(of: "https://") != nil ||
        url.description.lowercased().range(of: "mailto:") != nil {
        UIApplication.shared.openURL(url)
      }
    }
  return nil
}

# Additional context 
> ℹ Please replace this with any other context or screenshots about your feature request (optional).

**Comment by SvenTiigi** [comment] 2022-07-05 15:27
Hi @erank3,

the `YouTubePlayerKit` already handles opening external links.

https://github.com/SvenTiigi/YouTubePlayerKit/blob/main/Sources/WebView/YouTubePlayerWebView%2BWKUIDelegate.swift#L6-L29

https://github.com/SvenTiigi/YouTubePlayerKit/blob/main/Sources/WebView/YouTubePlayerWebView%2BWKNavigationDelegate.swift#L60

If you discovered an issue where a link doesn't get opened:
Please provide a repository where the problem can be reproduced.

**Comment by erank3** [comment] 2022-07-12 14:21
I'm working on main - 
Whenever I click on the 'YouTube' UI objects it opens Safari in a new window and leaves my app context, I would like the links to be opened in a popup 

See attached video with the problem

Thanks !

https://user-images.githubusercontent.com/3659732/178512612-3ff35ccd-ba80-4849-9951-d4ebb0aab54c.mov

**Comment by SvenTiigi** [comment] 2022-07-12 21:02
Hi @erank3,

Thanks for the explanation and the provided demo video.
In general opening links is not always referred to simple Web (HTTP) links as custom scheme and universal links are only supported by using the standard mechanism via `UIApplication.shared.open` and not via the `SFSafariViewController`.

Therefore `YouTubePlayerKit` relies on the system standards and is using `UIApplication.shared.open` or `NSWorkspace.shared.open` on macOS in order to open links.

Here is a great blog post explaining the topic in detail:
https://pspdfkit.com/blog/2019/open-links-in-safari-not-safari-view-controller/

**Comment by erank3** [comment] 2022-07-13 07:45
Thanks for replying, I don't understand the answer - 
are you saying it's not possible to use SFSafariViewController? it doesn't seems like those links are custom scheme nor universal links ...

Its it possible to explore an option of settings this via config?

**Comment by SvenTiigi** [comment] 2022-07-14 20:54
Hi @erank3,

Please checkout the feature branch [`feature/open-url-action`](https://github.com/SvenTiigi/YouTubePlayerKit/tree/feature/open-url-action) which now contains a configuration parameter to handle the URL via a custom action.

```swift
let youTubePlayer = YouTubePlayer(
    source: .url("..."),
    configuration: .init(
        openURLAction: .init { url in
            print("Open URL", url)
        }
    )
)
```

As already mentioned I'm currently not 100% sure if this change will be merged in the develop or main branch as opening links from an unknown source could lead to problems or unexpected behaviors when links are not opened via Safari (universal links & custom scheme urls).

Additionally, the [youtube-ios-player-helper](https://github.com/youtube/youtube-ios-player-helper) from YouTube is not making any kind of use of the `SFSafariViewController` which could potentially be, because of the YouTube Terms of Services.

**Comment by SvenTiigi** [comment] 2022-07-22 20:51
Closing this issue due to inactivity.
Feel free to re-open the issue at any time.

**Closed by SvenTiigi** 2022-07-22 20:51 UTC
Labels: question

**Comment by erank3** [comment] 2022-07-24 10:37
sorry for late response I was out, 
quick question sorry if obvious  - how to I add a branch with Swift package manager? 

I am writing: "feature/open-url-action" in the branch box however I package resolution fails  (see attachments
<img width="662" alt="Screen Shot 2022-07-24 at 13 36 32" src="https://user-images.githubusercontent.com/3659732/180643288-307b1d55-b583-4159-affc-2580ca123c09.png">
<img width="1086" alt="Screen Shot 2022-07-24 at 13 35 54" src="https://user-images.githubusercontent.com/3659732/180643290-05cef222-2491-4d88-be4f-ea2a38f740c1.png">
)

**Comment by erank3** [comment] 2022-07-24 11:19
never mind, I figured that out, 
the code on the [feature/open-url-action](https://github.com/SvenTiigi/YouTubePlayerKit/tree/feature/open-url-action)
works like charm, 
can you please merge it into main? 

I understand that it's grey area with YT TOS but I prefer having control on I chose to open external URLs.

Also - in the config you have the field: isUserInteractionEnabled
which defiantly goes against YT TOS (as they explicitly forbid blocking their UI controls)
so it would't be an exception.

Thanks again for the contribution.

**Comment by SvenTiigi** [comment] 2022-07-24 20:17
Hi @erank3,

please see the latest release [`1.2.0`](https://github.com/SvenTiigi/YouTubePlayerKit/releases/tag/1.2.0) which now contains the `openURLAction` parameter.

Additionally, your suggested idea of removing the `isUserInteractionEnabled` parameter was a great research and is now part of the latest release.

PS: The feature branch `feature/open-url-action` has been removed
